javascript-javascript3-week2
suvarna-ratna/hyf-homework pull request #15
Opened 2021-09-08 14:16 UTC by suvarna-ratna

feedback?

2021-09-12 10:55 UTC, florinmaticu commented on javascript/javascript3/week2/promise.js
> +      resolve();
There is a small mistake. A string argument is need for `resolve` function.
`Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?ts(2794)`
For example `resolve('timeout after x seconds')`

2021-09-12 10:56 UTC, florinmaticu commented on javascript/javascript3/week2/promise.js
> +      resolve();
There is a small mistake. A string argument is need for resolve function.
Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?ts(2794)

2021-09-12 11:00 UTC, florinmaticu requested changes
Visual promise program doesn't seem to work. The balls don't move to their final destination. For development purposes and debugging you can use https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
![image](https://user-images.githubusercontent.com/3575408/132984947-056f0945-e484-4896-bd76-328ed25f12ce.png)

2021-09-12 11:00 UTC, flom84 commented on javascript/javascript3/week2/promise.js
> +    resolve();
There is a small mistake. A string argument is need for resolve function.
`Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?ts(2794)`
For example resolve('timeout after x seconds')

2021-09-24 08:07 UTC, suvarna-ratna commented on javascript/javascript3/week2/promise.js
> +    resolve();
done

2021-09-24 08:07 UTC, merged